"use client";

import { ExternalLink } from "lucide-react";
import { Card, CardContent } from "@/components/ui/card";
import { Badge } from "@/components/ui/badge";
import { RedditIcon } from "@/components/dashboard/reddit-icon";
import {
  ANON_PREVIEW_COUNT,
  LockedThreadRow,
  SignupUnlockBar,
} from "@/components/dashboard/thread-gate";

export type GtmBriefThread = {
  id: string;
  sub: string;
  title: string;
  link: string;
  author?: string;
  updated?: string;
  score?: number;
  num_comments?: number;
};

export type GtmBrief = {
  run_id?: string;
  generated_at?: string;
  top_threads: GtmBriefThread[];
};

function ageLabel(updated?: string): string {
  if (!updated) return "";
  const ms = Date.now() - new Date(updated).getTime();
  const hours = ms / 3_600_000;
  if (hours < 1) return `${Math.max(1, Math.round(hours * 60))}m`;
  if (hours < 24) return `${Math.round(hours)}h`;
  const days = hours / 24;
  if (days < 7) return `${Math.round(days)}d`;
  return `${Math.round(days / 7)}w`;
}

function ThreadRow({ t, rank }: { t: GtmBriefThread; rank: number }) {
  return (
    <a
      href={t.link}
      target="_blank"
      rel="noreferrer"
      className="group/thread flex items-start gap-2 rounded-md px-1.5 py-1.5 transition-colors hover:bg-card/60"
    >
      <span className="mt-0.5 w-5 shrink-0 text-right font-mono text-[10px] tabular-nums text-brand/70 group-hover/thread:text-brand">
        {String(rank).padStart(2, "0")}
      </span>
      <div className="min-w-0 flex-1">
        <p className="line-clamp-2 text-xs text-foreground/85 group-hover/thread:text-foreground">
          {t.title}
        </p>
        <div className="mt-1 flex flex-wrap items-center gap-1.5 font-mono text-[10px] text-muted-foreground/60">
          <Badge
            variant="outline"
            className="h-4 border-brand/30 px-1 text-[10px] text-brand/80"
          >
            r/{t.sub}
          </Badge>
          {t.author && <span>u/{t.author}</span>}
          {t.updated && <span>· {ageLabel(t.updated)}</span>}
          {typeof t.score === "number" && <span>· {t.score} pts</span>}
          {typeof t.num_comments === "number" && (
            <span>· {t.num_comments} cmts</span>
          )}
        </div>
      </div>
      <ExternalLink className="mt-1 size-3 shrink-0 text-muted-foreground/40 opacity-0 transition-opacity group-hover/thread:opacity-100" />
    </a>
  );
}

function BriefHeader({ totalCount }: { totalCount: number }) {
  return (
    <div className="flex items-center justify-between gap-3 px-(--card-spacing)">
      <div className="flex min-w-0 items-center gap-1.5">
        <span className="font-heading text-[10px] tracking-widest uppercase text-muted-foreground/60">
          Signal
        </span>
        <span className="font-heading text-[10px] tracking-widest uppercase text-muted-foreground/30">
          ·
        </span>
        <span className="font-heading text-[10px] tracking-widest uppercase text-muted-foreground/60">
          Reddit market scan
        </span>
        <RedditIcon className="ml-1 size-3.5 opacity-80" />
      </div>
      <span className="shrink-0 font-mono text-[10px] tabular-nums text-muted-foreground/60">
        {totalCount} threads
      </span>
    </div>
  );
}

export function GtmBriefView({
  brief,
  isAuthed = true,
  signupHref = "/auth/sign-up",
}: {
  brief: GtmBrief;
  isAuthed?: boolean;
  signupHref?: string;
}) {
  const totalCount = brief.top_threads.length;
  const hiddenCount = Math.max(0, totalCount - ANON_PREVIEW_COUNT);
  const visibleThreads = isAuthed
    ? brief.top_threads
    : brief.top_threads.slice(0, ANON_PREVIEW_COUNT);

  return (
    <div className="space-y-6">
      {totalCount > 0 && (
        <Card>
          <BriefHeader totalCount={totalCount} />
          <CardContent className="space-y-0.5">
            {visibleThreads.map((t, i) => (
              <ThreadRow key={t.id} t={t} rank={i + 1} />
            ))}

            {!isAuthed && hiddenCount > 0 && (
              <SignupUnlockBar
                hiddenCount={hiddenCount}
                signupHref={signupHref}
              />
            )}

            {!isAuthed && hiddenCount > 0 && (
              <>
                {brief.top_threads
                  .slice(ANON_PREVIEW_COUNT)
                  .map((t, i) => (
                    <LockedThreadRow
                      key={t.id}
                      rank={i + 1 + ANON_PREVIEW_COUNT}
                      title={t.title}
                    />
                  ))}
              </>
            )}
          </CardContent>
        </Card>
      )}

      <p className="text-center font-heading text-[10px] tracking-widest uppercase text-muted-foreground/50">
        Generated by opencorp
        {brief.generated_at
          ? ` · ${new Date(brief.generated_at).toLocaleString()}`
          : ""}
      </p>
    </div>
  );
}
